// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOpU7O6NsD58-W-Ng4DuBm7l4316-HpPk',
    appId: '1:430320084749:web:cad4b8338206a9d994b244',
    messagingSenderId: '430320084749',
    projectId: 'cs184-hw2-c0bb4',
    authDomain: 'cs184-hw2-c0bb4.firebaseapp.com',
    storageBucket: 'cs184-hw2-c0bb4.appspot.com',
    measurementId: 'G-1CVB6RNJF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsu-HzLfaL_zh1rRqAvci1pJftj94CXo',
    appId: '1:430320084749:android:11b406388ef8530294b244',
    messagingSenderId: '430320084749',
    projectId: 'cs184-hw2-c0bb4',
    storageBucket: 'cs184-hw2-c0bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOmehxBlRpTc5A6n5-hOFdvMj0VEt414',
    appId: '1:430320084749:ios:85dc3dd6fd5907d494b244',
    messagingSenderId: '430320084749',
    projectId: 'cs184-hw2-c0bb4',
    storageBucket: 'cs184-hw2-c0bb4.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOmehxBlRpTc5A6n5-hOFdvMj0VEt414',
    appId: '1:430320084749:ios:b23442811653435c94b244',
    messagingSenderId: '430320084749',
    projectId: 'cs184-hw2-c0bb4',
    storageBucket: 'cs184-hw2-c0bb4.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
